name: Build Windows

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Create Build Folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force build

      - name: Compile Engine
        shell: pwsh
        run: |
          javac -d build source/*.java Project.java

      - name: Copy Assets
        shell: pwsh
        run: |
          Copy-Item assets build/assets -Recurse -Force
          Copy-Item arts build/arts -Recurse -Force

      - name: Create Manifest
        shell: pwsh
        run: |
          "Main-Class: Main`n" | Out-File -Encoding ASCII manifest.txt

      - name: Generate Jar
        shell: pwsh
        run: |
          jar cfm JackEngine.jar manifest.txt -C build .

      - name: Build EXE
        shell: pwsh
        run: |
          jpackage `
            --type exe `
            --name "JackEngine" `
            --input . `
            --main-jar JackEngine.jar `
            --main-class Main `
            --dest dist `
            --win-console

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: JackEngine-Windows
          path: dist/